Repository DovydasKi/CaffeineApp, pull requests merged in 2020-03, with the labels that each got.

#5 Prisijungimo lango logika
  Caffeine/Caffeine.xcodeproj/project.pbxproj
  Caffeine/Caffeine/Model/LoginViewModel.swift
  Caffeine/Caffeine/ViewControllers/LoginViewController.swift
  Caffeine/Caffeine/ViewControllers/SplashScreenViewController.swift
Labels: improvement

#6 Registration screen design w/o logic
  Caffeine/Caffeine.xcodeproj/project.pbxproj
  Caffeine/Caffeine/Model/InputValidation.swift
  Caffeine/Caffeine/Model/LoginViewModel.swift
  Caffeine/Caffeine/Model/RegisterVIewModel.swift
  Caffeine/Caffeine/Model/TextFieldConnectFields.swift
  Caffeine/Caffeine/ViewControllers/LoginViewController.swift
  Caffeine/Caffeine/ViewControllers/MainScreenViewController.swift
  Caffeine/Caffeine/ViewControllers/RegisterViewController.swift
  Caffeine/Caffeine/ViewControllers/SplashScreenViewController.swift
Labels: Feature

#8 Fixed constraints
  Caffeine/Caffeine/ViewControllers/RegisterViewController.swift
Labels: improvement

#9 Fixed login screen constraints for other devices
  Caffeine/Caffeine/ViewControllers/LoginViewController.swift
Labels: improvement

#10 [CAF-30]: Apatinis navigacijos langas
  Caffeine/Caffeine.xcodeproj/project.pbxproj
  Caffeine/Caffeine.xcodeproj/project.xcworkspace/xcuserdata/dovydaskiriliauskas.xcuserdatad/UserInterfaceState.xcuserstate
  Caffeine/Caffeine.xcodeproj/xcuserdata/dovydaskiriliauskas.xcuserdatad/xcdebugger/Breakpoints_v2.xcbkptlist
  Caffeine/Caffeine/Resources/Assets.xcassets/profile.imageset/Contents.json
  Caffeine/Caffeine/Resources/Assets.xcassets/profile.imageset/users1.png
  Caffeine/Caffeine/Resources/Assets.xcassets/profile.imageset/users2.png
  Caffeine/Caffeine/Resources/Assets.xcassets/profile.imageset/users3.png
  Caffeine/Caffeine/Resources/Assets.xcassets/reservation.imageset/Contents.json
  Caffeine/Caffeine/Resources/Assets.xcassets/reservation.imageset/reservation1.png
  Caffeine/Caffeine/Resources/Assets.xcassets/reservation.imageset/reservation2.png
  Caffeine/Caffeine/Resources/Assets.xcassets/reservation.imageset/reservation3.png
  Caffeine/Caffeine/Resources/Assets.xcassets/restaurant.imageset/Contents.json
  Caffeine/Caffeine/Resources/Assets.xcassets/restaurant.imageset/restaurant1.png
  Caffeine/Caffeine/Resources/Assets.xcassets/restaurant.imageset/restaurant2.png
  Caffeine/Caffeine/Resources/Assets.xcassets/restaurant.imageset/restaurant3.png
  Caffeine/Caffeine/Startup/SceneDelegate.swift
  Caffeine/Caffeine/ViewControllers/HomeScreenViewController.swift
  Caffeine/Caffeine/ViewControllers/SplashScreenViewController.swift
  Caffeine/Caffeine/ViewControllers/TabBarViewController.swift
Labels: Feature

#12 Created last registration screen w/ logic
  Caffeine/Caffeine.xcodeproj/project.pbxproj
  Caffeine/Caffeine/Model/RegistrationImageSelectionViewModel.swift
  Caffeine/Caffeine/Resources/Assets.xcassets/profileImage.imageset/Contents.json
  Caffeine/Caffeine/Resources/Assets.xcassets/profileImage.imageset/Pirma icona.png
  Caffeine/Caffeine/Resources/Assets.xcassets/profileImage.imageset/Pirma icona@2x.png
  Caffeine/Caffeine/Resources/Assets.xcassets/profileImage.imageset/Pirma icona@3x.png
  Caffeine/Caffeine/Resources/Assets.xcassets/profileImage2.imageset/Antra icona.png
  Caffeine/Caffeine/Resources/Assets.xcassets/profileImage2.imageset/Antra icona@2x.png
  Caffeine/Caffeine/Resources/Assets.xcassets/profileImage2.imageset/Antra icona@3x.png
  Caffeine/Caffeine/Resources/Assets.xcassets/profileImage2.imageset/Contents.json
  Caffeine/Caffeine/Resources/Assets.xcassets/profileImage3.imageset/Contents.json
  Caffeine/Caffeine/Resources/Assets.xcassets/profileImage3.imageset/Trečia icona.png
  Caffeine/Caffeine/Resources/Assets.xcassets/profileImage3.imageset/Trečia icona@2x.png
  Caffeine/Caffeine/Resources/Assets.xcassets/profileImage3.imageset/Trečia icona@3x.png
  Caffeine/Caffeine/Resources/Assets.xcassets/profileImage4.imageset/Contents.json
  Caffeine/Caffeine/Resources/Assets.xcassets/profileImage4.imageset/Ketvirta icona.png
  Caffeine/Caffeine/Resources/Assets.xcassets/profileImage4.imageset/Ketvirta icona@2x.png
  Caffeine/Caffeine/Resources/Assets.xcassets/profileImage4.imageset/Ketvirta icona@3x.png
  Caffeine/Caffeine/Resources/Assets.xcassets/profileImage5.imageset/Contents.json
  Caffeine/Caffeine/Resources/Assets.xcassets/profileImage5.imageset/Penkta icona.png
  Caffeine/Caffeine/Resources/Assets.xcassets/profileImage5.imageset/Penkta icona@2x.png
  Caffeine/Caffeine/Resources/Assets.xcassets/profileImage5.imageset/Penkta icona@3x.png
  Caffeine/Caffeine/Resources/Assets.xcassets/profileImage6.imageset/Contents.json
  Caffeine/Caffeine/Resources/Assets.xcassets/profileImage6.imageset/šešta icona.png
  Caffeine/Caffeine/Resources/Assets.xcassets/profileImage6.imageset/šešta icona@2x.png
  Caffeine/Caffeine/Resources/Assets.xcassets/profileImage6.imageset/šešta icona@3x.png
  Caffeine/Caffeine/ViewControllers/RegistrationConfirmationViewController.swift
  Caffeine/Caffeine/ViewControllers/RegistrationImageSelectionViewController.swift
  Caffeine/Caffeine/ViewControllers/SplashScreenViewController.swift
Labels: Feature

#13 Refactoring and minor bug fixes
  Caffeine/Caffeine/Model/RegistrationImageSelectionViewModel.swift
  Caffeine/Caffeine/Resources/Assets.xcassets/.DS_Store
  Caffeine/Caffeine/ViewControllers/HomeScreenViewController.swift
  Caffeine/Caffeine/ViewControllers/LoginViewController.swift
  Caffeine/Caffeine/ViewControllers/MainScreenViewController.swift
  Caffeine/Caffeine/ViewControllers/RegisterViewController.swift
  Caffeine/Caffeine/ViewControllers/RegistrationConfirmationViewController.swift
  Caffeine/Caffeine/ViewControllers/RegistrationImageSelectionViewController.swift
  Caffeine/Caffeine/ViewControllers/SplashScreenViewController.swift
Labels: improvement

#14 [CAF-31]: Kaviniu zemelapis
  Caffeine/Caffeine.xcodeproj/project.pbxproj
  Caffeine/Caffeine.xcodeproj/project.xcworkspace/xcuserdata/dovydaskiriliauskas.xcuserdatad/UserInterfaceState.xcuserstate
  Caffeine/Caffeine.xcodeproj/xcuserdata/dovydaskiriliauskas.xcuserdatad/xcdebugger/Breakpoints_v2.xcbkptlist
  Caffeine/Caffeine/Model/RestaurantsViewModel.swift
  Caffeine/Caffeine/Resources/Assets.xcassets/cancel.imageset/Contents.json
  Caffeine/Caffeine/Resources/Assets.xcassets/cancel.imageset/cancel.png
  Caffeine/Caffeine/Resources/Assets.xcassets/coffeePin.imageset/Contents.json
  Caffeine/Caffeine/Resources/Assets.xcassets/coffeePin.imageset/coffee2.png
  Caffeine/Caffeine/Resources/Assets.xcassets/sauletekis.imageset/Contents.json
  Caffeine/Caffeine/Resources/Assets.xcassets/sauletekis.imageset/download.jpeg
  Caffeine/Caffeine/Support Files/Info.plist
  Caffeine/Caffeine/ViewControllers/PropertyCardViewController.swift
  Caffeine/Caffeine/ViewControllers/RestaurantsViewController.swift
  Caffeine/Caffeine/ViewControllers/TabBarViewController.swift
Labels: Feature

#15 Profilio langas
  Caffeine/Caffeine.xcodeproj/project.pbxproj
  Caffeine/Caffeine/Model/ProfileViewModel.swift
  Caffeine/Caffeine/Model/Shadow.swift
  Caffeine/Caffeine/Resources/Assets.xcassets/orangeMain.colorset/Contents.json
  Caffeine/Caffeine/ViewControllers/ProfileInformationViewController.swift
  Caffeine/Caffeine/ViewControllers/ProfileReservationCustomTableViewCell.swift
  Caffeine/Caffeine/ViewControllers/ProfileReservationViewController.swift
  Caffeine/Caffeine/ViewControllers/TabBarViewController.swift
Labels: Feature

#16 [CAF-5]: Artimiausios kavines radimas
  Caffeine/Caffeine.xcodeproj/project.pbxproj
  Caffeine/Caffeine.xcodeproj/project.xcworkspace/xcuserdata/dovydaskiriliauskas.xcuserdatad/UserInterfaceState.xcuserstate
  Caffeine/Caffeine.xcodeproj/xcuserdata/dovydaskiriliauskas.xcuserdatad/xcdebugger/Breakpoints_v2.xcbkptlist
  Caffeine/Caffeine/Resources/Assets.xcassets/.DS_Store
  Caffeine/Caffeine/Resources/Assets.xcassets/profileImage3.imageset/Contents.json
  Caffeine/Caffeine/Resources/Assets.xcassets/profileImage3.imageset/šešta icona.png
  Caffeine/Caffeine/Resources/Assets.xcassets/profileImage3.imageset/šešta icona@2x.png
  Caffeine/Caffeine/Resources/Assets.xcassets/profileImage3.imageset/šešta icona@3x.png
  Caffeine/Caffeine/Resources/Assets.xcassets/profileImage6.imageset/Contents.json
  Caffeine/Caffeine/Resources/Assets.xcassets/profileImage6.imageset/Trečia icona.png
  Caffeine/Caffeine/Resources/Assets.xcassets/profileImage6.imageset/Trečia icona@2x.png
  Caffeine/Caffeine/Resources/Assets.xcassets/profileImage6.imageset/Trečia icona@3x.png
  Caffeine/Caffeine/Support Files/Info.plist
  Caffeine/Caffeine/ViewControllers/ProfileReservationViewController.swift
  Caffeine/Caffeine/ViewControllers/RestaurantsViewController.swift
Labels: Feature

#17 [CAF-6]: Kavinės meniu
  Caffeine/Caffeine.xcodeproj/project.pbxproj
  Caffeine/Caffeine/Model/DetailedCoffeeViewModel.swift
  Caffeine/Caffeine/Resources/Assets.xcassets/blackCoffee.imageset/Contents.json
  Caffeine/Caffeine/Resources/Assets.xcassets/blackCoffee.imageset/dark.jpg
  Caffeine/Caffeine/Resources/Assets.xcassets/cappuccino.imageset/Contents.json
  Caffeine/Caffeine/Resources/Assets.xcassets/cappuccino.imageset/cappuccino.jpg
  Caffeine/Caffeine/Resources/Assets.xcassets/flatWhite.imageset/Contents.json
  Caffeine/Caffeine/Resources/Assets.xcassets/flatWhite.imageset/flatWhite.jpg
  Caffeine/Caffeine/Resources/Assets.xcassets/lCupFilled.imageset/Contents.json
  Caffeine/Caffeine/Resources/Assets.xcassets/lCupFilled.imageset/lCupFilled.pdf
  Caffeine/Caffeine/Resources/Assets.xcassets/lCupOutline.imageset/Contents.json
  Caffeine/Caffeine/Resources/Assets.xcassets/lCupOutline.imageset/lCupOutline.pdf
  Caffeine/Caffeine/Resources/Assets.xcassets/latte.imageset/Contents.json
  Caffeine/Caffeine/Resources/Assets.xcassets/latte.imageset/latte.jpg
  Caffeine/Caffeine/Resources/Assets.xcassets/mCupFilled.imageset/Contents.json
  Caffeine/Caffeine/Resources/Assets.xcassets/mCupFilled.imageset/mCupFilled.pdf
  Caffeine/Caffeine/Resources/Assets.xcassets/mCupOutline.imageset/Contents.json
  Caffeine/Caffeine/Resources/Assets.xcassets/mCupOutline.imageset/mCupOutline.pdf
  Caffeine/Caffeine/Resources/Assets.xcassets/mocha.imageset/Contents.json
  Caffeine/Caffeine/Resources/Assets.xcassets/mocha.imageset/mocha.jpg
  Caffeine/Caffeine/Resources/Assets.xcassets/sCupFilled.imageset/Contents.json
  Caffeine/Caffeine/Resources/Assets.xcassets/sCupFilled.imageset/sCupFilled.pdf
  Caffeine/Caffeine/Resources/Assets.xcassets/sCupOutline.imageset/Contents.json
  Caffeine/Caffeine/Resources/Assets.xcassets/sCupOutline.imageset/sCupOutline.pdf
  Caffeine/Caffeine/Resources/Assets.xcassets/whiteCoffee.imageset/Contents.json
  Caffeine/Caffeine/Resources/Assets.xcassets/whiteCoffee.imageset/white.jpg
  Caffeine/Caffeine/ViewControllers/CafeDrinkMenuViewController.swift
  Caffeine/Caffeine/ViewControllers/DetailedCoffeeViewController.swift
  Caffeine/Caffeine/ViewControllers/PropertyCardViewController.swift
  Caffeine/CaffeineTests/Info.plist
Labels: Feature

#18 [CAF-12]: Staliuko rezervacijos langas [1 dalis]
  Caffeine/Caffeine.xcodeproj/project.pbxproj
  Caffeine/Caffeine.xcodeproj/project.xcworkspace/xcuserdata/dovydaskiriliauskas.xcuserdatad/UserInterfaceState.xcuserstate
  Caffeine/Caffeine/Model/ReservationDetailsViewModel.swift
  Caffeine/Caffeine/Resources/Assets.xcassets/placeholderOrange.colorset/Contents.json
  Caffeine/Caffeine/Resources/Assets.xcassets/profileImage3.imageset/Contents.json
  Caffeine/Caffeine/Resources/Assets.xcassets/profileImage3.imageset/Trečia icona.png
  Caffeine/Caffeine/Resources/Assets.xcassets/profileImage3.imageset/Trečia icona@2x.png
  Caffeine/Caffeine/Resources/Assets.xcassets/profileImage3.imageset/Trečia icona@3x.png
  Caffeine/Caffeine/Resources/Assets.xcassets/profileImage6.imageset/Contents.json
  Caffeine/Caffeine/Resources/Assets.xcassets/profileImage6.imageset/šešta icona.png
  Caffeine/Caffeine/Resources/Assets.xcassets/profileImage6.imageset/šešta icona@2x.png
  Caffeine/Caffeine/Resources/Assets.xcassets/profileImage6.imageset/šešta icona@3x.png
  Caffeine/Caffeine/Resources/Assets.xcassets/textOrange.colorset/Contents.json
  Caffeine/Caffeine/ViewControllers/LoginViewController.swift
  Caffeine/Caffeine/ViewControllers/MainScreenViewController.swift
  Caffeine/Caffeine/ViewControllers/RegisterViewController.swift
  Caffeine/Caffeine/ViewControllers/RegistrationConfirmationViewController.swift
  Caffeine/Caffeine/ViewControllers/RegistrationImageSelectionViewController.swift
  Caffeine/Caffeine/ViewControllers/ReservationDetailsViewController.swift
  Caffeine/Caffeine/ViewControllers/ReservationTypeViewController.swift
  Caffeine/Caffeine/ViewControllers/RestaurantsViewController.swift
  Caffeine/Caffeine/ViewControllers/SplashScreenViewController.swift
  Caffeine/Caffeine/ViewControllers/TabBarViewController.swift
Labels: Feature

#23 Antra rezervavimo dalis + bugfixai
  Caffeine/Caffeine.xcodeproj/project.xcworkspace/xcuserdata/dovydaskiriliauskas.xcuserdatad/UserInterfaceState.xcuserstate
  Caffeine/Caffeine/Model/ReservationDetailsViewModel.swift
  Caffeine/Caffeine/ViewControllers/ProfileReservationViewController.swift
  Caffeine/Caffeine/ViewControllers/ReservationDetailsViewController.swift
  Caffeine/Caffeine/ViewControllers/ReservationTypeViewController.swift
Labels: Feature, bugfix

#24 Sveciu kiekio pasirinkimas
  Caffeine/Caffeine.xcodeproj/project.pbxproj
  Caffeine/Caffeine.xcodeproj/project.xcworkspace/xcuserdata/dovydaskiriliauskas.xcuserdatad/UserInterfaceState.xcuserstate
  Caffeine/Caffeine.xcodeproj/xcshareddata/xcschemes/Caffeine.xcscheme
  Caffeine/Caffeine/Model/ReservationDetailsViewModel.swift
  Caffeine/Caffeine/ViewControllers/GuestAmmountViewController.swift
  Caffeine/Caffeine/ViewControllers/ReservationDetailsViewController.swift
  Caffeine/Caffeine/ViewControllers/ReservationTypeViewController.swift
  Caffeine/Caffeine/ViewControllers/TabBarViewController.swift
Labels: Feature

#25 [CAF-8]: Pokalbio temos pasirinkimas [1 dalis]
  Caffeine/Caffeine.xcodeproj/project.pbxproj
  Caffeine/Caffeine/Model/NewUserMeetupPurposeModel.swift
  Caffeine/Caffeine/Resources/Assets.xcassets/.DS_Store
  Caffeine/Caffeine/Resources/Assets.xcassets/Image.imageset/Contents.json
  Caffeine/Caffeine/Resources/Assets.xcassets/orangeBolt.imageset/Contents.json
  Caffeine/Caffeine/Resources/Assets.xcassets/orangeBolt.imageset/orangeBolt.png
  Caffeine/Caffeine/ViewControllers/NewUserMeetupTopicsCustomTableViewCell.swift
  Caffeine/Caffeine/ViewControllers/NewUserMeetupTopicsViewController.swift
  Caffeine/Caffeine/ViewControllers/RegisterViewController.swift
  Caffeine/Caffeine/ViewControllers/RegistrationConfirmationViewController.swift
  Caffeine/Caffeine/ViewControllers/RegistrationImageSelectionViewController.swift
Labels: Feature

#26 [CAF-8]: Pokalbio temos pasirinkimas [2 dalis]
  Caffeine/Caffeine.xcodeproj/project.pbxproj
  Caffeine/Caffeine.xcodeproj/project.xcworkspace/contents.xcworkspacedata
  Caffeine/Caffeine/Model/Coffee.swift
  Caffeine/Caffeine/Model/MeetupPurposeModel.swift
  Caffeine/Caffeine/Model/Topic.swift
  Caffeine/Caffeine/Model/User.swift
  Caffeine/Caffeine/ViewControllers/CafeDrinkMenuViewController.swift
  Caffeine/Caffeine/ViewControllers/NewUserMeetupTopicsViewController.swift
  Caffeine/Caffeine/ViewControllers/ProfileInformationViewController.swift
  Caffeine/Caffeine/ViewControllers/ProfileMeetupTopicsCustomTableViewCell.swift
  Caffeine/Caffeine/ViewControllers/ProfileMeetupTopicsViewController.swift
  Caffeine/Caffeine/ViewControllers/ProfileReservationViewController.swift
Labels: Feature

#27 [CAF-14]: Staliuko rezervacijos atšaukimas
  Caffeine/Caffeine.xcodeproj/project.pbxproj
  Caffeine/Caffeine/Model/ActionSheet.swift
  Caffeine/Caffeine/ViewControllers/ProfileInformationViewController.swift
  Caffeine/Caffeine/ViewControllers/ProfileMeetupTopicsViewController.swift
  Caffeine/Caffeine/ViewControllers/ProfileReservationCustomTableViewCell.swift
  Caffeine/Caffeine/ViewControllers/ProfileReservationViewController.swift
  Caffeine/Caffeine/ViewControllers/SplashScreenViewController.swift
Labels: Feature
